apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template: 
    metadata:
      labels:
        app: myapp
    spec:
      containers: 
      - name: logodevops
        image: logodevops
        resources:
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 3000

